README.md

Hi 
I was a little unsure about the format to use for listing the tech hubs so I decided to create a pull request with one first, if accepted, then I can add others using the same format.
Regards,
Sam

Added CCHub

---

README.md

I added iDEA hub, both the Lagos and Cross River locations.

Added iDEA hub

---

README.md

I added with tech hubs with their websites and addresses, namely:
LitCaf
TPX Hub
360 Creative Hub

Added new Tech Hubs in Lagos

---

README.md

I added tech hubs in Owerri to the List.

Tech-Hubs List update

---

README.md

I confirmed that **_LeadPath_** is now **_LeadSpace_**, and they have another location at Ojodu, Lagos.

Changed LeadPath To LeadSpace and added new location

---

README.md

Good evening Fire Evangelist
The Anambra State entry occurs two times, so i removed one of them.

'removing_duplicate_entry_for_Anambra_state'

---

README.md

Added IC7 Hub in Abuja.
Note that provided link takes you to their IG page as they do not have a functional website.
Hub is functional though.
Also Added bullets to Hubs with bullets missing

Added IC7 Hub Abuja

---

README.md

I added "The smart hub" to the list for hubs in Abuja.

Added "The Smart Hub" to the list of hubs in Abuja

---

README.md

I've added more co-working spaces in Lagos, and a few others in Abuja and Port Harcourt.

More co-working spaces in Lagos

---

README.md

I added Vatebra Tech Hub which is in Lagos State.

Added Vatebra Tech Hub in Lagos

---

README.md

add tech-hub

---

README.md

Added LearnFactory Nigeria in Aba Abia.

Add learnFactory Abia

---

README.md

Added LPI Hub

---

README.md

I added uplift Hub which is in Bauchi state.

Uplift hub 

---

README.md

I added new hubs to ogun state,also differentiate between ogun and Lagos.

Add new hubs in ogun state

---

README.md

Added Hub67 and AimtoGet Hub in Ibadan, Oyo state.

Added two hubs in Ibadan

---

README.md

Initialized and added a few hubs in niger

Added hubs in Niger state

---

README.md

Added two new hubs in kwara iLab and Cirkle Labs

Updated Hubs in Kwara 

---

README.md

Added MicrolabACE in Ife, Osun State.
The website for the hub is still under construction, added a link to their twitter page instead.

Added MicrolabACE

---

README.md

Added 2 Tech hubs in Abeokuta. RenownedTech (Open Hub) is quite small but completely free to use once you are a recognised member while 720Degrees is bigger and more organized with subscriptions starting at 5000 Naira

added 2 tech hubs in Abeokuta

---

README.md

added Adamawa state, including four tech hubs, more coming

Adamawa state

---

README.md

exington hub is operated by Lexington technologies, located at the heart of Kaduna state’ s capital, with focus on strengthening innovation, technology, creativity, entrepreneurship towards building an ICT oriented society . This is inline with Lexington’ s urge of equipping the community and upcoming generation to become proficient with the ICT skills needed to thrive everlasting solutions to existing problems.

Added Lexington Hub in Kaduna

---

README.md

KAD ICT HUB is world-class Hub that trains in web/ mobile app, hardware, AI, IoT, blockchain technologies. An outsourcing firm which companies can outsource their tech needs.
PS: If it is no problem, I will appreciate if you add me as a collaborator

Add KAD ICT HUB

---

README.md

Added 3 tech hubs in Edo state including the popular Edo innovation hub
Kindly review and merge

:memo: Added 3 tech hubs in Edo state

---

README.md

I added the newly lunched aiivon tech hub branch at makurdi, benue state.

Added aiivon tech hub branch in makurdi, benue state

---

README.md

New Tech Hub in Adamawa State

---

README.md

Zonetech Park, and Grazac hubs located in Lagos, and Ogun states respectively have been included in the list.

Added Zonetech park Lagos state, and Grazac co-working space Ogun state

---

README.md

I added Nasarawa state and two tech hubs in Nasarawa state:
-Mtech Innovation hub
-DNI Hubs

Added a new state and two tech hubs
